# Generated by Django 6.0.4 on 2026-04-19 04:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'candidates',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('normalized_name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('file_url', models.TextField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=20, null=True)),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('parse_metadata', models.JSONField(blank=True, default=dict)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='main.candidate')),
            ],
            options={
                'db_table': 'resumes',
            },
        ),
        migrations.CreateModel(
            name='ParseJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('parser_version', models.CharField(blank=True, max_length=50, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parse_job', to='main.resume')),
            ],
            options={
                'db_table': 'parse_jobs',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=255)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('gpa', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='main.resume')),
            ],
            options={
                'db_table': 'education',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('issuer', models.CharField(blank=True, max_length=255, null=True)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('credential_url', models.URLField(blank=True, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='main.resume')),
            ],
            options={
                'db_table': 'certifications',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='main.resume')),
            ],
            options={
                'db_table': 'work_experiences',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ResumeSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proficiency_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20, null=True)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('is_inferred', models.BooleanField(default=False)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_skills', to='main.resume')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_skills', to='main.skill')),
            ],
            options={
                'db_table': 'resume_skills',
                'unique_together': {('resume', 'skill')},
            },
        ),
    ]
